[tool.poetry]
name = "solaredge"
version = "0.1.0"
description = ""
authors = ["Tim Savage <tim@savage.company>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pymodbus = "^3.7.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
